#!/usr/bin/env fish

function install_fasd
  sudo add-apt-repository ppa:aacebedo/fasd
  sudo apt-get update
  sudo apt-get install fasd
  omf install fasd
end

function install_fzf
  git clone --depth 1 https://github.com/junegunn/fzf.git /tmp/.fzf
  /tmp/.fzf/install
  rm -rf /tmp/.fzf
  omf install fzf
end

function debinstall
  argparse f/format= v/version= -- $argv
  wget (printf "$_flag_format" "$_flag_version") -O /tmp/.tmp.deb
  sudo dpkg -i /tmp/.tmp.deb
  rm -f /tmp/.tmp.deb
end

function install_fd
  debinstall -f "https://github.com/sharkdp/fd/releases/download/v8.2.1/fd-musl_%s_amd64.deb" -v 8.2.1 $argv
end

function install_bat
  debinstall -f "https://github.com/sharkdp/bat/releases/download/v0.18.0/bat-musl_%s_amd64.deb" -v 0.18.0
end

switch $argv[1]
  case fasd
    install_fasd $argv[2..]
  case fzf
    install_fzf $argv[2..]
  case fd
    install_fd $argv[2..]
  case bat
    install_bat $argv[2..]
  case '*'
    echo $argv[1] is not supported yet.
end

