#!/usr/bin/env python3

from color import fail
import os
from sys import platform
import shutil
from subprocess import check_call
from sysutil import SCRIPT_DIR, run_cmd

SCRIPT_DIR = os.path.abspath(os.path.dirname(__file__))


def setup_key_linux():
    shutil.move("/usr/share/X11/xkb/symbols/us", "/usr/share/X11/xkb/symbols/us.bk")
    run_cmd(f"sudo cp {os.path.join(SCRIPT_DIR, 'us')} /usr/share/X11/xkb/symbols/us")


if __name__ == "__main__":
    if platform in ("linux", "linux2"):
        setup_key_linux()
    else:
        fail(f"OS {platform} not supported")
