#!/usr/bin/env python3

import argparse
import os
from color import okay, info
from sysutil import run_cmd, has, link, HOME
from tempfile import TemporaryDirectory


def install_stack():
    info("Installing stack...")
    run_cmd(f"curl -sSL https://get.haskellstack.org/ | sh")
    okay("Success.")

def install_kmonad():
    install_stack()
    info("Cloning kmonad...")
    with TemporaryDirectory() as tmpdir:
        run_cmd(f"git clone https://github.com/kmonad/kmonad {tmpdir}")
        info("Building and installing kmonad...")
        run_cmd(f"stack install {tmpdir}")
        


def install_configs():
    info("Linking keyboard files...")
    link("kmonad/cherry.kbd", os.path.join(HOME, ".cherry.kbd"))
    info("Creating kmonad service...")
    link("kmonad/kmonad.service", "/etc/systemd/system/kmonad.service")
    info("Starting kmonad service...")
    run_cmd("systemctl start kmonad")
    info("Registering kmonad service...")
    run_cmd("systemctl enable kmonad")
    okay("Success.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Setup xmonad.")
    parser.add_argument("--skip_config", const=True, default=False,
                        action='store_const', help="skip linking kbd files")
    args = parser.parse_args()
    if not has("kmonad"):
        install_kmonad()
    args.skip_config or install_configs()
