#!/usr/bin/env python3

import os
from color import okay, info
from sysutil import os_pick, run_cmd, link_to_home, has

NVIM_VERSION = "nightly"


def install_nvim_linux():
    run_cmd(
        "curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
    )
    run_cmd("sudo rm -rf /opt/nvim")
    run_cmd("sudo tar -C /opt -xzf nvim-linux64.tar.gz")
    os.system("fish -c 'fish_add_path /opt/nvim-linux64/bin'")
    run_cmd("pip3 install pynvim")
    assert has("nvim")


def install_nvim_darwin():
    run_cmd(f"brew install nvim")
    assert has("nvim")


install_nvim = os_pick(linux=install_nvim_linux, darwin=install_nvim_darwin)

if __name__ == "__main__":
    if has("nvim"):
        okay(f"Neovim already exists.")
    else:
        info("Installing neovim...")
        install_nvim()
        okay("Success.")

    link_to_home(".config/nvim")
