#!/usr/bin/env python3

from color import fail
import os
from sys import platform
import shutil
from subprocess import check_call
import argparse

from sysutil import SCRIPT_DIR, run_cmd

SCRIPT_DIR = os.path.abspath(os.path.dirname(__file__))
LAYOUT_FILE = "/usr/share/X11/xkb/symbols/us"
BACKUP_FILE = LAYOUT_FILE+".bk"


def setup_key_linux():
    shutil.move(LAYOUT_FILE, BACKUP_FILE)
    run_cmd(f"sudo cp {os.path.join(SCRIPT_DIR, 'us')} /usr/share/X11/xkb/symbols/us")

def reset_key_linux():
    assert os.path.exists(BACKUP_FILE)
    run_cmd(f"sudo cp {BACKUP_FILE} {LAYOUT_FILE}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--reset", "-r", action="store_true")
    args = parser.parse_args()
    if platform in ("linux", "linux2"):
        reset_key_linux() if args.reset else setup_key_linux()
    else:
        fail(f"OS {platform} not supported")
