#!/usr/bin/env python3

from color import fail, okay, info
import os
from sysutil import HOME, link_to_home, run_cmd, has
from subprocess import check_output, check_call


def install_zsh_linux():
    if has("apt"):
        run_cmd("sudo apt install zsh")
    elif has("pacman"):
        run_cmd("pacman -S zsh")
    elif has("dnf"):
        run_cmd("dnf install zsh")
    else:
        fail("Failed to install zsh. Your package manager is not supported yet.")


def install_ohmyzsh():
    install_sh = check_output(
        ["curl", "-fsSL", "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"])
    check_call(['sh', '-c', install_sh])


if __name__ == "__main__":
    if not has("zsh"):
        info("Installing zsh...")
        install_zsh_linux()
        okay("zsh installed.")
        info("Setting zsh as default shell...")
        which_zsh = check_output(["which", "zsh"])
        run_cmd(f'chsh -s {which_zsh.strip()}')
        okay("zsh now is the default.")
    if not has(os.path.join(HOME, ".oh_my_zsh")):
        install_ohmyzsh()
    link_to_home(".oh_my_zsh/custom")
