#!/usr/bin/env bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
CONFDIR=${XDG_CONFIG_HOME:-$HOME/.config}

if ! which fish; then
  echo "Installing fish..."
  sudo apt-add-repository ppa:fish-shell/release-3
  sudo apt-get update
  sudo apt-get install fish
else
  echo "Fish found"
fi

if ! which starfish; then
  echo "Installing starship..."
  curl -sS https://starship.rs/install.sh | sh
else
  echo "starship found"
fi

echo setting fish to default shell
which fish | sudo tee -a /etc/shells
chsh -s fish

test -f "$CONFDIR/fish/completions/bazel.fish" && echo "Bazel completion exists." || \
  { echo "Setting up bazel completion";
    pip3 install absl-py &&
    python3 $SCRIPTDIR/generate_fish_completion.py --bazel=$(which bazel) --output=$CONFDIR/fish/completions/bazel.fish; }

if ! omf --version; then
  echo "Installing oh-my-fish"
  curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
else
  echo "omf found"
fi

echo "Linking config folders"
test -d "$CONFDIR/fish" || mkdir -p $CONFDIR/fish
ln -s $SCRIPTDIR/fish/functions $CONFDIR/fish/functions
rm -rf $CONFDIR/omf
ln -s $SCRIPTDIR/fish/omf  $CONFDIR/omf
echo "Linking results:"
ls -l $CONFDIR/fish/functions
ls -l $CONFDIR/omf

fish -c "fish_add_path $HOME/.local/bin"
