#!/usr/bin/env fish

brew update
brew install poetry conan

mkdir -p $HOME/.config/pip

if not set -q ARTIFACTORY_USER
	echo set ARTIFACTORY_USER to $USER
	set -xg ARTIFACTORY_USER $USER
end

if not set -q ARTIFACTORY_PASS
	read -s -P "Artifactory Token (https://geckorobotics.jfrog.io/): " arti_token
	set -xg ARTIFACTORY_PASS $arti_token
end

echo "
[global]
index-url = https://$ARTIFACTORY_USER:$ARTIFACTORY_PASS@geckorobotics.jfrog.io/artifactory/api/pypi/pypi/simple
" >> $HOME/.config/pip/pip.conf

poetry config repositories.geckorobotics-pypi https://geckorobotics.jfrog.io/artifactory/api/pypi/pypi/simple
poetry config http-basic.geckorobotics-pypi $ARTIFACTORY_USER $ARTIFACTORY_PASS

set -xU POETRY_HTTP_BASIC_GECKOROBOTICS_PYPI_USERNAME $ARTIFACTORY_USER
set -xU POETRY_HTTP_BASIC_GECKOROBOTICS_PYPI_PASSWORD $ARTIFACTORY_PASS
set -xU POETRY_HTTP_BASIC_GECKOROBOTICS_PYPI_LOCAL_USERNAME $ARTIFACTORY_USER
set -xU POETRY_HTTP_BASIC_GECKOROBOTICS_PYPI_LOCAL_PASSWORD $ARTIFACTORY_PASS
set -xU ARTIFACTORY_PASSWORD $ARTIFACTORY_PASS

conan remote add conan https://geckorobotics.jfrog.io/artifactory/api/conan/conan
conan remote login conan $ARTIFACTORY_USER -p $ARTIFACTORY_PASS

conan remote add conan-local https://geckorobotics.jfrog.io/artifactory/api/conan/conan-local
conan remote login conan-local $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD

