package main

// ---- Shared guard script ---------------------------------------------------

const guardScriptTmpl = `#!/bin/bash
# Auto-generated by deploy-bedtime.go — do not edit manually.
# Schedules a shutdown 5 min from now if current time is in the sleep window.

hour=$(date +%H)
minute=$(date +%M)
now=$(( 10#$hour * 60 + 10#$minute ))

bedtime=$(( {{.BedtimeHour}} * 60 + {{.BedtimeMinute}} ))
wakeup=$(( {{.WakeupHour}}   * 60 + {{.WakeupMinute}}  ))

in_window=0
if (( bedtime > wakeup )); then
    # window wraps midnight  e.g. 21:00 – 06:00
    (( now >= bedtime || now < wakeup )) && in_window=1
else
    # window within same day e.g. 01:00 – 05:00
    (( now >= bedtime && now < wakeup )) && in_window=1
fi

if (( in_window )); then
    if ! {{ .IsPending }}; then
        {{ .ScheduleShutdown }}
    fi
fi
`

// ---- Linux templates (systemd) ---------------------------------------------

const linuxServiceUnitTmpl = `# Auto-generated by deploy-bedtime.go — do not edit manually.
[Unit]
Description=Bedtime shutdown at {{printf "%02d" .BedtimeHour}}:{{printf "%02d" .BedtimeMinute}}

[Service]
Type=oneshot
ExecStart=/sbin/shutdown now
`

const linuxTimerUnitTmpl = `# Auto-generated by deploy-bedtime.go — do not edit manually.
[Unit]
Description=Shutdown daily at {{printf "%02d" .BedtimeHour}}:{{printf "%02d" .BedtimeMinute}}

[Timer]
OnCalendar=*-*-* {{printf "%02d" .BedtimeHour}}:{{printf "%02d" .BedtimeMinute}}:00
Persistent=true

[Install]
WantedBy=timers.target
`

const linuxGuardServiceUnitTmpl = `# Auto-generated by deploy-bedtime.go — do not edit manually.
[Unit]
Description=Schedule shutdown if resumed during sleep hours
After=network.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/bedtime-shutdown.sh

[Install]
WantedBy=multi-user.target sleep.target
`

// ---- macOS templates (launchd) ---------------------------------------------

// Hard shutdown plist — launchd fires this at the exact bedtime.
const macOSShutdownPlistTmpl = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by deploy-bedtime.go — do not edit manually. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.bedtime.shutdown</string>

    <key>ProgramArguments</key>
    <array>
        <string>/sbin/shutdown</string>
        <string>-h</string>
        <string>now</string>
    </array>

    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>   <integer>{{.BedtimeHour}}</integer>
        <key>Minute</key> <integer>{{.BedtimeMinute}}</integer>
    </dict>

    <key>RunAtLoad</key><false/>
</dict>
</plist>
`

// Guard plist — runs the shell script at boot and every 60 s so resumes are caught quickly.
const macOSGuardPlistTmpl = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by deploy-bedtime.go — do not edit manually. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.bedtime.guard</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/bedtime-shutdown.sh</string>
    </array>

    <key>RunAtLoad</key><true/>

    <!-- Re-check every 60 s so wake-from-sleep is caught within a minute -->
    <key>StartInterval</key><integer>60</integer>
</dict>
</plist>
`
